### ISSUE TITLE
Does this do what you expect? 

### ISSUE THREAD

**Issue by aric87** [chieakiba/quiz-app#3]
https://github.com/chieakiba/quiz-app/blob/master/js/app.js#L36

I would expect this to run once, and return the element. When you reference the variable later, on line 48, it's already run.

**Comment by chieakiba** [comment]
Yea, you're right. I originally did that because it kept on displaying it even when I tried doing display: none via css. I commented out line 48 and tested it and ran fine so I'll take that out from app.js. Thanks!
Another person opened an issue letting me know to NOT use .hide()/.show() so I'll see how I can incorporate that and make the show/hide transition smoother.
